# Oracle deployment values
# Override values for the oracle-db chart dependency
# This is used for full Oracle EE 19c deployment (LIGHTWEIGHT=0)

oracle-db:
  oracle_sid: ORCLCDB
  oracle_pdb: ORCLPDB1
  oracle_pwd: oracle
  oracle_characterset: AL32UTF8
  oracle_edition: enterprise

  enable_archivelog: false

  persistence: null

  replicas: 1
  loadBalService: false

  image: omygod613/oe:19.3.0.0
  imagePullPolicy: Always
  imagePullSecrets: regcred
